### PR TITLE
Added a command for fish shell

### PR DESCRIPTION
**Pull request by marcoil**
This script makes lsi work on my setup (Ubuntu 20.04 + fish), although to select a directory the key is Alt+Enter.

### CODE REVIEW

**Comment by Araxeus** [comment]
what is the status variable?
 `if test $status -eq 0`

isn't `if [ -n "$output" ]` enough?

also, I think `$argv` should be surrounded with quotes to avoid weird bugs

**Comment by marcoil** [comment]
> what is the status variable?

The result of the last command, the bash script checks it so I added it. I can take it out, but I still think it's better to use fish's `test` command.

> I think `$argv` should be surrounded with quotes to avoid weird bugs

Do you want all arguments passed to lsi to be considered just one argument to ls-argument? In that case yes, it should have double quotes.

**Comment by Araxeus** [comment]
> The result of the last command, the bash script checks it so I added it. I can take it out, but I still think it's better to use fish's test command.

Ok if you think its necessary

> Do you want all arguments passed to lsi to be considered just one argument to ls-argument? In that case yes, it should have double quotes.

well lsi can optionally receive one arg and its the starting path

from what I understand from you, if `$argv` is double quoted and I execute the command `lsi big folder`
it will pass to lsi the string `big folder`?
if that is the case then its totally fine, seems to add support for spaces in folder names 😝

**Comment by marcoil** [comment]
> if `$argv` is double quoted and I execute the command `lsi big folder`
> it will pass to lsi the string `big folder`?

Exactly. If `ls-interactive` only wants one parameter, then it makes sense to quote argv. I'll patch it.

**Comment by Araxeus** [comment]
Thank you :)

**Pull request merged**
